[tool.poetry]
name = "internutar"
version = "0.1.0"
description = ""
authors = ["Yii Kuo Chong <byu1628@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
